language: php

php:
  - 5.2

dist: precise

script:
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml tests/backlog/backlogTests.php
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml tests/profile/profileTests.php
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml tests/projects/projectsTests.php
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml tests/selectedProject/selectedProjectTests.php
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml tests/sprint/sprintTest.php
