language: php

php:
  - '5.2'
  - '5.4'
  - '5.6'
  - '7.0'
  - nightly

dist: precise

before_install:
  - ./install-phpunit.sh

script:
  - ./runTests.sh

after_script:
  - rm -f tests/configTest.ini
