language: php

php:
  - nightly

dist: trusty

script:
  - phpunit --log-junit logTests/$( date '+%Y-%m-%d' )-test.xml  --configuration  tests/phpunit.xml tests

after_script:
  - rm -f tests/configTest.ini
