language: php
php:
  - '5.2'
  - '5.4'
  - '5.6'
  - '7.0'
  - nightly
dist: precise
services:
  - mysql
install:
  - composer install
before_install:
  - echo 123456789 | mysql -u root -p gfloret < src/bdd.sql
  - touch tests/configTest.ini
  - echo '[database]' >> tests/configTest.ini
  - echo 'servername = 127.0.0.1' >> tests/configTest.ini
  - echo 'username = root' >> tests/configTest.ini
  - echo 'password = 123456789' >> tests/configTest.ini
  - echo 'dbname = gfloret' >> tests/configTest.ini
  - ./install-phpunit.sh

script:
  - ./runTests.sh

after_script:
  - rm -f tests/configTest.ini
